# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Implementers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'implementers',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('implementer', models.CharField(max_length=30)),
                ('id_implementer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Implementers')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
