# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='implementers',
            old_name='name',
            new_name='name_implementers',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='name',
            new_name='title_tasks',
        ),
    ]
