# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20160407_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='implementer',
        ),
    ]
