# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_remove_tasks_implementer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='implementer',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
