# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_tasks_implementer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implementer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'implementer',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('implementer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Implementer')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='id_implementer',
        ),
        migrations.DeleteModel(
            name='Implementers',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
